# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(236, 336)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_4.setObjectName("label_4")
        self.idEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.idEdit.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.idEdit.setObjectName("idEdit")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameEdit.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.bakingEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.bakingEdit.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.bakingEdit.setObjectName("bakingEdit")
        self.typeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.typeEdit.setGeometry(QtCore.QRect(90, 110, 113, 20))
        self.typeEdit.setObjectName("typeEdit")
        self.descEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.descEdit.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.descEdit.setObjectName("descEdit")
        self.priceEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceEdit.setGeometry(QtCore.QRect(90, 170, 113, 20))
        self.priceEdit.setObjectName("priceEdit")
        self.volumeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.volumeEdit.setGeometry(QtCore.QRect(90, 200, 113, 20))
        self.volumeEdit.setObjectName("volumeEdit")
        self.addBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addBtn.setGeometry(QtCore.QRect(14, 242, 201, 51))
        self.addBtn.setText("")
        self.addBtn.setObjectName("addBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 236, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Название"))
        self.label_3.setText(_translate("MainWindow", "Прожарка"))
        self.label_5.setText(_translate("MainWindow", "Вкус"))
        self.label_6.setText(_translate("MainWindow", "Цена"))
        self.label_7.setText(_translate("MainWindow", "Объем"))
        self.label_4.setText(_translate("MainWindow", "Зерно/молотый"))
